### PR TITLE
Mining: Fix CreateCoinStake

### PR DESCRIPTION
**Pull request by Katano-Sukune**
Hi XPC dev!

- Set feerate (2XPC/KB)
There is a problem that it does not stake for a long time.
I think that it fail to estimate fee.

- Make it to write error message
It will help you if this idea is wrong.

### CODE REVIEW

**Comment by serisia** [comment]
Thank you for your work!
As it seemed that this issue did not occur on Testnet, I thought that the fee was likely to be the cause, but I was helped because I did not get time.

By the way, why is it that the feerate is 2XPC/kB?
Is 2XPC/kB better than 1XPC/kB?

**Comment by Katano-Sukune** [comment]
It must be minrelaytxfee or more (0.1XPC/KB)

**Comment by serisia** [comment]
I got it. Thank you so much!

**Comment by yes-maxheart** [comment]
Thank you so much!
I will merge this!

**Pull request merged**
