### PR TITLE
Scripts and tools: Add Dockerfile and compose sample file

### PR DESCRIPTION
**Pull request by moochannel**
This Dockerfile contains `xpchaind`, `xpchain-cli`, `xpchain-tx`. An `xpchain-qt` is **not** included for running a container as a daemon.

`docker-compose.yml.sample` is a sample for building Docker image and running Docker container. To use it, copy that file into `docker-compose.yml`, and edit the `docker-compose.yml` as you need.

### CODE REVIEW

**Comment by serisia** [comment]
Would you like to write to expose ports 8762 and 18762? (These are rpc ports.)
I think that want to open 8798 and 8762 when daemon works in mainnet, however want to open 18798 and 18762 when daemon works in testnet.

I suggest to write all ports to "expose" section in Dockerfile and write mainnet ports as port to open and testnet ports as comment into docker-compose.yml.sample.

**Comment by moochannel** [comment]
It sure is.
I'll update soon.

**Comment by serisia** [comment]
LGTM 👍 
The container works fine in my environment!

**Comment by yes-maxheart** [comment]
👍

**Pull request merged**
